In [60]:
# import sleep to show output for some time period 
from time import sleep  
from IPython.display import clear_output

print("Hello World!")
sleep(2) 
clear_output(wait=True)
print("Hello lol!")




Hello lol!


In [71]:
import numpy as np
#sudoku puzzle, '0' as blank 
puzzle1 =np.array([[2,5,7,8,0,1,0,4,0],
                   [9,8,0,6,7,0,5,0,1],
                   [0,0,3,5,4,0,0,2,0],
                   [0,3,0,0,5,0,0,0,6],
                   [7,0,0,0,9,0,2,1,0],
                   [0,0,0,2,0,4,7,0,3],
                   [0,0,8,0,1,5,9,0,0],
                   [0,6,1,0,0,8,0,0,0],
                   [4,0,9,0,6,0,0,0,5] ])
puzzle2 = np.array([ [5,1,7,6,0,0,0,3,4],
                     [2,8,9,0,0,4,0,0,0],
                     [3,4,6,2,0,5,0,9,0],
                     [6,0,2,0,0,0,0,1,0],
                     [0,3,8,0,0,6,0,4,7],
                     [0,0,0,0,0,0,0,0,0],
                     [0,9,0,0,0,0,0,7,8],
                     [7,0,3,4,0,0,5,6,0],
                     [0,0,0,0,0,0,0,0,0]])


In [3]:
#this function checks if the guess'z' for the row y, column x is possible by checking the x and y axis and subgrid

def possible(y,x,z,puzzle):
    #checks for possible duplicates of attempt 'z' in row 'y'
    for i in range(0,9):
        if puzzle[y,i] == z:
            return False
    #checks for possible duplicates of attempt 'z' in row 'x'
    for i in range(0,9):
        if puzzle[i,x] == z:
            return False
    #checks for possible duplicates of attempt 'z' in subgrid
    for k,l in zip(range(0,7,3),range(3,10,3)):          #creates subgrid rows 0-2,3-5,6-8
        for i,j in zip(range(0,7,3),range(3,10,3)):      #creates subgrid columns 0-2,3-5,6-8
            if k<= y < l and i<= x < j:                  #if guess 'z' is located in this subgrid...
                subgrid =puzzle[k:l,i:j]
                if z in set(subgrid.flat):               #if guess 'z' has a duplicate in subgrid
                    return False
    
    return True



In [73]:
#this function solves the sudoku puzzle array 'sudoku'
#attempt counter is the number of times a sudoku element is guessed in an empty space. just enter "0" to start
def solve(sudoku,attempt_counter):
    sudoku_solved = sudoku
    for y in range(9):
        for x in range(9):
            if sudoku_solved[y,x]==0:                           #checks if there is an empty space in row 'y', column 'x'
                for i in range(0,10):
                    if possible(y,x,i,sudoku_solved):
                        #clear_output(wait=True)
                        #print(sudoku_solved)
                        sudoku_solved[y,x] = i                  #if there is an empty space, attempt 'i' if 'i' is possible
                        #sleep(0.1) 
                        #clear_output(wait=True)
                        #print(sudoku_solved)
                        attempt_counter += 1
                        solve(sudoku_solved,attempt_counter)    #run solve() again for the next empty space 
                        sudoku_solved[y,x] = 0                  #returns attempt 'i' to zero if the previous solve function failed to find a possible attempt for the next zero and is returned
                return                                          #if attempt 'i'is no longer possible, return to previous solve function
    print(sudoku_solved)                                        #print solved sudoku there are no more blank spaces
    print(attempt_counter)
   

In [74]:
solve(puzzle1,0)


[[2 5 7 8 3 1 6 4 9]
 [9 8 4 6 7 2 5 3 1]
 [6 1 3 5 4 9 8 2 7]
 [8 3 2 1 5 7 4 9 6]
 [7 4 5 3 9 6 2 1 8]
 [1 9 6 2 8 4 7 5 3]
 [3 7 8 4 1 5 9 6 2]
 [5 6 1 9 2 8 3 7 4]
 [4 2 9 7 6 3 1 8 5]]
47


In [75]:
solve(puzzle2,0)


[[5 1 7 6 9 8 2 3 4]
 [2 8 9 1 3 4 7 5 6]
 [3 4 6 2 7 5 8 9 1]
 [6 7 2 8 4 9 3 1 5]
 [1 3 8 5 2 6 9 4 7]
 [9 5 4 7 1 3 6 8 2]
 [4 9 5 3 6 2 1 7 8]
 [7 2 3 4 8 1 5 6 9]
 [8 6 1 9 5 7 4 2 3]]
61
